jokes = [
  "Two peanuts were walking down the street. One was a salted.",
  "I got a reversible jacket for Christmas, I can't wait to see how it turns out.",
  "I burned 2000 calories today, I left my food in the oven for too long.",
  "Where did you learn to make ice cream? Sunday school.",
  "As I suspected, someone has been adding soil to my garden. The plot thickens.",
  "Did you know the first French fries weren't actually cooked in France? They were cooked in Greece.",
  "What do you call a dad that has fallen through the ice? A Popsicle.",
  "Did you hear about the cheese who saved the world? It was Legend-dairy!",
  "I saw a documentary on TV last night about how they put ships together. It was rivetting.",
  "A butcher accidentally backed into his meat grinder and got a little behind in his work that day.",
  "I always wanted to look into why I procrastinate, but I keep putting it off.",
  "How do you teach a kid to climb stairs? There is a step by step guide.",
  "What do you call a pig with three eyes? Piiig.",
  "A girl once asked me what my heart desired, apparently blood, oxygen and neural messages were all wrong answers.",
  "Why do pumpkins sit on people’s porches? They have no hands to knock on the door.",
  "What do vegetarian zombies eat? Grrrrrainnnnnssss.",
  "\"Hey, dad, did you get a haircut?\" \"No, I got them all cut.\"",
  "A man walks into a bar and orders helicopter flavor chips. The barman replies “sorry mate we only do plain”.",
  "Ben & Jerry's really need to improve their operation. The only way to get there is down a rocky road.",
  "Have you heard the story about the magic tractor? It drove down the road and turned into a field.",
  "What did the sea say to the sand? \"We have to stop meeting like this.\"",
  "Did you hear about the cheese who saved the world? It was Legend-dairy!",
  "Why are basketball players messy eaters? Because they are always dribbling.",
  "What do you call a fake noodle? An impasta.",
  "What do you get if you cross a turkey with a ghost? A poultry-geist!",
  "I got an A on my origami assignment when I turned my paper into my teacher.",
  "The other day, my wife asked me to pass her lipstick but I accidentally passed her a glue stick. She still isn't talking to me.",
  "What do you get when you cross a bee and a sheep? A bah-humbug.",
  "I heard there was a new store called Moderation. They have everything there.",
  "What do you call an Argentinian with a rubber toe? Roberto.",
  "Did you hear that the police have a warrant out on a midget psychic ripping people off? It reads “Small medium at large.”",
  "I cut my finger cutting cheese. I know it may be a cheesy story but I feel grate now.",
  "How does a penguin build it’s house? Igloos it together.",
  "I went to the doctor today and he told me I had type A blood but it was a type O.",
  "What is a vampire's favorite fruit? A blood orange.",
  "Why did the opera singer go sailing? They wanted to hit the high Cs.",
  "Why did the chicken get a penalty? For fowl play.",
  "When is a door not a door? When it's ajar.",
  "Why are fish easy to weigh? Because they have their own scales.",
  "To be Frank, I'd have to change my name.",
  "How do you make a water bed more bouncy? You use Spring Water.",
  "Did you hear about the two thieves who stole a calendar? They each got six months.",
  "What do prisoners use to call each other? Cell phones.",
  "Two guys walked into a bar, the third one ducked.",
  "Ever wondered why bees hum? It's because they don't know the words.",
  "How does a dyslexic poet write? Inverse.",
  "What has a bed that you can’t sleep in? A river.",
  "I saw an ad in a shop window, \"Television for sale, $1, volume stuck on full\", I thought, \"I can't turn that down\".",
  "Why is there always a gate around cemeteries? Because people are always dying to get in.",
  "Why did the worker get fired from the orange juice factory? Lack of concentration.",
  "Today a man knocked on my door and asked for a small donation towards the local swimming pool. I gave him a glass of water.",
  "What did the ocean say to the beach? Thanks for all the sediment.",
  "A beekeeper was indicted after he confessed to years of stealing at work. They charged him with emBEEzlement.",
  "Dermatologists are always in a hurry. They spend all day making rash decisions.",
  "I started a new business making yachts in my attic this year...the sails are going through the roof.",
  "I considered building the patio by myself. But I didn't have the stones.",
  "I used to think I was indecisive, but now I'm not sure.",
  "What's the difference between a poorly dressed man on a tricycle and a well dressed man on a bicycle? Attire.",
  "Did you hear about the submarine industry? It really took a dive...",
  "A man is washing the car with his son. The son asks...... \"Dad, can’t you just use a sponge?\"",
  "Why was the big cat disqualified from the race? Because it was a cheetah.",
  "How come the stadium got hot after the game? Because all of the fans left.",
  "Today a girl said she recognized me from vegetarian club, but I’m sure I’ve never met herbivore.",
  "Why do bees have sticky hair? Because they use honey combs!",
  "Why do scuba divers fall backwards into the water? Because if they fell forwards they’d still be in the boat.",
  "I got fired from the transmission factory, turns out I didn't put on enough shifts...",
  "My son is studying to be a surgeon, I just hope he makes the cut.",
  "Did you hear about the bread factory burning down? They say the business is toast.",
  "Why are oranges the smartest fruit? Because they are made to concentrate.",
  "What has three letters and starts with gas? A Car.",
  "What do you give a sick lemon? Lemonaid.",
  "What is red and smells like blue paint? Red paint!",
  "What’s E.T. short for? He’s only got little legs.",
  "Whoever invented the knock-knock joke should get a no bell prize.",
  "Where do you take someone who has been injured in a Peek-a-boo accident? To the I.C.U.",
  "The rotation of earth really makes my day.",
  "I just got fired from a florist, apparently I took too many leaves.",
  "The shovel was a ground-breaking invention.",
  "What do you call a crowd of chess players bragging about their wins in a hotel lobby? Chess nuts boasting in an open foyer.",
  "Who did the wizard marry? His ghoul-friend.",
  "When I left school, I passed every one of my exams with the exception of Greek Mythology. It always was my Achilles elbow.",
  "Animal Fact #25: Most bobcats are not named bob.",
  "They laughed when I said I wanted to be a comedian – they’re not laughing now.",
  "My boss told me to have a good day. So I went home...",
  "What is a centipede's favorite Beatle song? I want to hold your hand, hand, hand, hand...",
  "How do you find Will Smith in the snow? Look for fresh prints.",
  "Why do cows not have toes? They lactose!",
  "No matter how kind you are, German children are kinder.",
  "Where does batman go to the bathroom? The batroom.",
  "I was so proud when I finished the puzzle in six months, when on the side it said three to four years.",
  "What's the difference between a guitar and a fish? You can tune a guitar but you can't \"tuna\" fish!",
  "What do you call an eagle who can play the piano? Talonted!",
  "Why does it take longer to get from 1st to 2nd base, than it does to get from 2nd to 3rd base? Because there’s a Shortstop in between!",
  "I was shocked when I was diagnosed as colorblind... It came out of the purple.",
  "Is the pool safe for diving? It deep ends.",
  "Don’t interrupt someone working intently on a puzzle. Chances are, you’ll hear some crosswords.",
  "How was the snow globe feeling after the storm? A little shaken."
]
